# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Partial clone
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.email $EMAIL
          git config --global user.name $NAME
          git clone --filter=blob:none --no-checkout --depth 1  --sparse $REPO repo
          cd repo
          git sparse-checkout init --cone
          git sparse-checkout add "New folder"
          git checkout
          ls
          touch apple
          git add -A
          git commit -m "hello"
          git push
        env:
            NAME=Fawaz Ahmed
            EMAIL=fawazahmed0@hotmail.com
          
          
          

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          python --version
